# Generated by Django 4.2.19 on 2025-04-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techCLA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='item_images/default.jpg', null=True, upload_to='item_images/'),
        ),
    ]
