# Generated by Django 4.2.19 on 2025-04-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techCLA', '0002_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
