# Generated by Django 4.2.19 on 2025-04-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techCLA', '0003_borrowrequest_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestaccess',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
